/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stock;

/**
 *
 * @author Asus
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        BtnMainPurch = new javax.swing.JLabel();
        BtnMainSales = new javax.swing.JLabel();
        BtnMainProduct = new javax.swing.JLabel();
        BtnMainLog = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BtnMainVendor = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 620));

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 840, 40));

        BtnMainPurch.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        BtnMainPurch.setForeground(new java.awt.Color(255, 255, 255));
        BtnMainPurch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnMainPurch.setText("PUCHASE");
        BtnMainPurch.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 8, true));
        BtnMainPurch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnMainPurchMouseClicked(evt);
            }
        });
        jPanel1.add(BtnMainPurch, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 160, 210));

        BtnMainSales.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        BtnMainSales.setForeground(new java.awt.Color(255, 255, 255));
        BtnMainSales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnMainSales.setText("SALES");
        BtnMainSales.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 8, true));
        BtnMainSales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnMainSalesMouseClicked(evt);
            }
        });
        jPanel1.add(BtnMainSales, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 70, 160, 210));

        BtnMainProduct.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        BtnMainProduct.setForeground(new java.awt.Color(255, 255, 255));
        BtnMainProduct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnMainProduct.setText("PRODUCT");
        BtnMainProduct.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 8, true));
        BtnMainProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnMainProductMouseClicked(evt);
            }
        });
        jPanel1.add(BtnMainProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 160, 210));

        BtnMainLog.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        BtnMainLog.setForeground(new java.awt.Color(255, 255, 255));
        BtnMainLog.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnMainLog.setText("LOGOUT");
        BtnMainLog.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 8, true));
        BtnMainLog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnMainLogMouseClicked(evt);
            }
        });
        jPanel1.add(BtnMainLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 160, 210));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 8, true));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 330, 160, 210));

        BtnMainVendor.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        BtnMainVendor.setForeground(new java.awt.Color(255, 255, 255));
        BtnMainVendor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnMainVendor.setText("VENDOR");
        BtnMainVendor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 8, true));
        BtnMainVendor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnMainVendorMouseClicked(evt);
            }
        });
        jPanel1.add(BtnMainVendor, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 160, 210));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vecteezy-abstract-geometric-green-background_WS0321_generated.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 620));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 620));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnMainVendorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMainVendorMouseClicked
        Vendor v = new Vendor();
        v.setVisible(true);
    }//GEN-LAST:event_BtnMainVendorMouseClicked

    private void BtnMainPurchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMainPurchMouseClicked
        Purchase pu = new Purchase();
        pu.setVisible(true);
    }//GEN-LAST:event_BtnMainPurchMouseClicked

    private void BtnMainSalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMainSalesMouseClicked
        Sales s = new Sales();
        s.setVisible(true);
    }//GEN-LAST:event_BtnMainSalesMouseClicked

    private void BtnMainProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMainProductMouseClicked
        Product pr = new Product();
        pr.setVisible(true);
    }//GEN-LAST:event_BtnMainProductMouseClicked

    private void BtnMainLogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMainLogMouseClicked
        Login lg = new Login();
        lg.setVisible(true);
        
        Main m = new Main();
        this.setVisible(false);
    }//GEN-LAST:event_BtnMainLogMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BtnMainLog;
    private javax.swing.JLabel BtnMainProduct;
    private javax.swing.JLabel BtnMainPurch;
    private javax.swing.JLabel BtnMainSales;
    private javax.swing.JLabel BtnMainVendor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
